# Generated by Django 4.0.6 on 2022-07-18 22:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('alias', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('usuario', models.CharField(max_length=80, verbose_name='Nombre de usuario')),
                ('imagen', models.ImageField(default='-', upload_to='imagenes/')),
                ('email', models.EmailField(default='-', max_length=254)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.get_current_timezone)),
                ('pais_alias', models.ForeignKey(default='AR', on_delete=django.db.models.deletion.PROTECT, to='aplicacion.pais')),
            ],
        ),
        migrations.CreateModel(
            name='objeto_artisitico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=1500)),
                ('tipo', models.CharField(choices=[('IMG', 'Imagen'), ('VID', 'Video'), ('AUD', 'Audio'), ('OTRO', 'Otro')], default='OTRO', max_length=10)),
                ('fecha', models.DateTimeField()),
                ('ref', models.CharField(max_length=500)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.artista')),
            ],
        ),
        migrations.CreateModel(
            name='coleccionista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coleccion', models.ManyToManyField(to='aplicacion.objeto_artisitico')),
                ('usuario', models.ForeignKey(max_length=80, on_delete=django.db.models.deletion.PROTECT, to='aplicacion.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.usuario'),
        ),
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('privilegios', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.usuario')),
            ],
        ),
    ]
