# Generated by Django 4.0.6 on 2022-07-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleccionista',
            name='coleccion',
        ),
        migrations.RemoveField(
            model_name='coleccionista',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='objeto_artisitico',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pais_alias',
        ),
        migrations.DeleteModel(
            name='administrador',
        ),
        migrations.DeleteModel(
            name='artista',
        ),
        migrations.DeleteModel(
            name='coleccionista',
        ),
        migrations.DeleteModel(
            name='objeto_artisitico',
        ),
        migrations.DeleteModel(
            name='pais',
        ),
    ]
