# Generated by Django 4.0.6 on 2022-07-20 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Usuario',
            name='pais_alias',
            field=models.ForeignKey(default='AR', on_delete=django.db.models.deletion.PROTECT, to='aplicacion.pais', verbose_name='Pais de origen'),
        ),
    ]
