# Generated by Django 4.0.6 on 2022-07-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_remove_usuario_fecha_alta'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to='imagenes/')),
            ],
        ),
    ]
